# Generated by Django 5.0.6 on 2024-05-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favoriteJoke', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
